version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=notesapp
      - POSTGRES_USER=ki3ani
      - POSTGRES_PASSWORD=omniman2023
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
